name: Python application

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pexpect python-dotenv stockfish pytest-mock
    - name: Set dummy OpenAI API key for tests
      run: echo "OPENAI_API_KEY=dummy" >> $GITHUB_ENV
    - name: Run pytest (passwordless test mode)
      run: |
        export CHESS_APP_TEST_MODE=1
        pytest --ignore=tests/test_login_integration.py
